### ISSUE TITLE
libIlmImf-2_5.so.25: cannot open shared object file

### ISSUE THREAD

**Issue by utdrmac** [dmitri-mcguckin/octoprint-stuff#4]
I'm not sure what to do here to fix this issue. 

```
$ python3.9 -m venv webcamd
$ cd webcamd/
$ source bin/activate
$ pip3.9 install webcamd
...
Successfully installed PIL-Tools-1.1.0 Pillow-9.4.0 certifi-2022.12.7 charset-normalizer-3.1.0 idna-3.4 numpy-1.24.2 opencv-python-4.5.3.56 requests-2.28.2 urllib3-1.26.15 webcamd-1.0.1

$ webcamd --help
Traceback (most recent call last):
  File "/home/pi/webcamd/bin/webcamd", line 5, in <module>
    from webcamd.__main__ import main
  File "/home/pi/webcamd/lib/python3.9/site-packages/webcamd/__main__.py", line 1, in <module>
    import cv2
  File "/home/pi/webcamd/lib/python3.9/site-packages/cv2/__init__.py", line 5, in <module>
    from .cv2 import *
ImportError: libIlmImf-2_5.so.25: cannot open shared object file: No such file or directory


$ lsb_release -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 10 (buster)
Release:	10
Codename:	buster

$ uname -a
Linux raspicam 5.10.103-v7+ #1529 SMP Tue Mar 8 12:21:37 GMT 2022 armv7l GNU/Linux
```

**Comment by Gaofan666** [comment]
i have the same issue

**Comment by Gaofan666** [comment]
maybe you can run this command to download the lib:  `sudo apt-get insall libopenexr23` or `sudo apt-get insall libopenexr25`
